import {useEffect,useRef,useState} from 'react';
import {ParticleRenderer} from './renderer/ParticleRenderer';
import {creatures,type CreatureId} from './creatures/presets';
import {defaults,type Controls} from './state/controls';

const ranges:[keyof Controls,string,number,number,number][]=[['speed','Animation speed',0,3,.01],['scale','Body scale',.3,2.5,.01],['appendages','Appendages',0,24,1],['pulse','Pulse',0,3,.01],['turbulence','Turbulence / drift',0,2,.01],['size','Particle size',.5,8,.1],['density','Particle density',10000,250000,5000],['trail','Trail persistence',0,1,.01],['glow','Glow / bloom',0,3,.01],['hue','Hue',0,1,.01],['saturation','Saturation',0,2,.01],['brightness','Brightness',.2,2,.01],['deformation','Math deformation',0,3,.01],['phase','Phase field',.1,3,.01]];
const quality={eco:25000,balanced:50000,high:100000,ultra:250000} as const;
type Quality=keyof typeof quality;
type Bench={average:number;low:number;ratio:number;samples:number};
const emptyBench=():Bench=>({average:0,low:0,ratio:0,samples:0});

export default function App(){
 const host=useRef<HTMLDivElement|null>(null),engine=useRef<ParticleRenderer|null>(null),pausedRef=useRef(false),samples=useRef<number[]>([]);
 const [id,setId]=useState<CreatureId>('jellyfish'),[controls,setControls]=useState(defaults),[paused,setPaused]=useState(false),[fps,setFps]=useState(0),[qualityMode,setQualityMode]=useState<Quality>('balanced'),[bench,setBench]=useState<Bench>(emptyBench);
 const creature=creatures.find(c=>c.id===id)!;pausedRef.current=paused;
 const clearBench=()=>{samples.current=[];setBench(emptyBench())};
 useEffect(()=>{if(!host.current)return;engine.current=new ParticleRenderer(host.current);engine.current.update(creature,controls);let raf=0,last=performance.now(),frames=0,mark=last;const loop=()=>{engine.current?.render(pausedRef.current);const now=performance.now(),dt=now-last;last=now;if(!pausedRef.current&&dt>0&&dt<250){samples.current.push(1000/dt);if(samples.current.length>600)samples.current.shift()}frames++;if(now-mark>=1000){const instant=Math.round(frames*1000/(now-mark));setFps(instant);const values=samples.current,average=values.length?values.reduce((a,b)=>a+b,0)/values.length:0,sorted=[...values].sort((a,b)=>a-b),low=sorted.length?sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.01))]:0;setBench({average:Math.round(average),low:Math.round(low),ratio:engine.current?.getPixelRatio()||0,samples:values.length});frames=0;mark=now}raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);engine.current?.dispose();engine.current=null}},[]);
 useEffect(()=>{engine.current?.update(creature,controls)},[creature,controls]);
 const set=(k:keyof Controls,v:number)=>setControls(x=>({...x,[k]:v}));
 const applyQuality=(q:Quality)=>{clearBench();setQualityMode(q);setControls(x=>({...x,density:quality[q]}))};
 const reset=()=>{clearBench();setControls({...defaults,appendages:creature.appendages,density:quality[qualityMode]});setPaused(false)};
 const randomize=()=>setControls(x=>({...x,speed:+(.3+Math.random()*2).toFixed(2),pulse:+(Math.random()*2).toFixed(2),turbulence:+(Math.random()*1.4).toFixed(2),deformation:+(.3+Math.random()*2.4).toFixed(2),hue:Math.random()}));
 return <main><div ref={host} className="stage"/><header><div><span className="eyebrow">PROCEDURAL BIOLOGY / 001</span><h1>Marine <em>Motion</em></h1></div><div className="transport"><button onClick={()=>setPaused(!paused)}>{paused?'Play':'Pause'}</button><button onClick={reset}>Reset</button><button onClick={randomize}>Randomize</button><button onClick={()=>document.documentElement.requestFullscreen?.()}>Fullscreen</button></div></header><aside><section><label>Creature</label><div className="creatures">{creatures.map(c=><button key={c.id} className={id===c.id?'active':''} onClick={()=>{clearBench();setId(c.id);setControls({...defaults,appendages:c.appendages,density:quality[qualityMode]})}}>{c.name}</button>)}</div></section><section><label>Quality</label><div className="creatures">{(Object.keys(quality) as Quality[]).map(q=><button key={q} className={qualityMode===q?'active':''} onClick={()=>applyQuality(q)}>{q} · {(quality[q]/1000).toFixed(0)}k</button>)}</div></section><section className="telemetry"><label>Performance</label><div className="metrics"><span>Current <b>{fps||'—'} FPS</b></span><span>Average <b>{bench.average||'—'} FPS</b></span><span>1% low <b>{bench.low||'—'} FPS</b></span><span>Pixel ratio <b>{bench.ratio||'—'}×</b></span><span>Samples <b>{bench.samples}</b></span></div><button className="clear-bench" onClick={clearBench}>Clear benchmark</button></section><section className="controls">{ranges.map(([k,label,min,max,step])=><div className="control" key={k}><label>{label}<output>{controls[k]}</output></label><input type="range" min={min} max={max} step={step} value={controls[k]} onChange={e=>set(k,+e.target.value)}/></div>)}</section></aside><footer><span>{controls.density.toLocaleString()} PARTICLES</span><span>{fps||'—'} FPS</span><span>GPU PARAMETRIC FIELD</span><span>{creature.body.toUpperCase()} TOPOLOGY</span></footer></main>;}