import * as THREE from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import { AfterimagePass } from 'three/examples/jsm/postprocessing/AfterimagePass.js';
import { vertex, fragment } from '../shaders/particle';
import type { Creature } from '../creatures/presets';
import type { Controls } from '../state/controls';
const color=(s:string)=>new THREE.Color(s);
const low=()=>{const m=(navigator as Navigator&{deviceMemory?:number}).deviceMemory,c=navigator.hardwareConcurrency||8;return Boolean((m&&m<=4)||c<=4)};
const isHeadless=()=>typeof navigator!=='undefined'&&/HeadlessChrome/i.test(navigator.userAgent);
export class ParticleRenderer{
 renderer:THREE.WebGLRenderer;composer:EffectComposer;bloom:UnrealBloomPass;afterimage:AfterimagePass;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(45,1,.1,100);material!:THREE.ShaderMaterial;points!:THREE.Points;count=0;pointer=new THREE.Vector2(99,99);cameraTarget=new THREE.Vector2();start=performance.now();private resizeObserver:ResizeObserver;private disposed=false;private readonly lowPerformance=low();private readonly maxParticles=this.lowPerformance?50000:250000;private readonly pixelRatioCap=this.lowPerformance?1.25:2;private readonly enableParallax=!isHeadless();
 private readonly onPointerMove=(e:PointerEvent)=>{const r=this.renderer.domElement.getBoundingClientRect(),x=((e.clientX-r.left)/r.width)*2-1,y=-((e.clientY-r.top)/r.height)*2+1;this.pointer.set(x,y);if(this.enableParallax)this.cameraTarget.set(x*.24,y*.16)};private readonly onPointerLeave=()=>{this.pointer.set(99,99);if(this.enableParallax)this.cameraTarget.set(0,0)};
 getParticleLimit(){return this.maxParticles}getPixelRatio(){return this.renderer.getPixelRatio()}getParticleCount(){return this.count}
 constructor(private host:HTMLElement){host.querySelectorAll('canvas[data-marine-renderer="true"]').forEach(c=>c.remove());this.renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance'});this.renderer.domElement.dataset.marineRenderer='true';this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.pixelRatioCap));this.renderer.setClearColor(0x030713,1);this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.82;host.appendChild(this.renderer.domElement);this.camera.position.z=4;this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.55,.35,.82);this.afterimage=new AfterimagePass(.58);this.composer.addPass(this.bloom);this.composer.addPass(this.afterimage);this.resize();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.renderer.domElement.addEventListener('pointermove',this.onPointerMove,{passive:true});this.renderer.domElement.addEventListener('pointerleave',this.onPointerLeave,{passive:true})}
 resize(){if(this.disposed)return;const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.renderer.setSize(w,h,false);this.composer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 build(requested:number){const n=Math.min(requested,this.maxParticles);if(this.points){this.scene.remove(this.points);this.points.geometry.dispose();this.material.dispose()}this.count=n;const seed=new Float32Array(n),u=new Float32Array(n),v=new Float32Array(n),part=new Float32Array(n);for(let i=0;i<n;i++){seed[i]=Math.random();u[i]=Math.random();v[i]=Math.random();part[i]=i%16}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(n*3),3));g.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));g.setAttribute('aU',new THREE.BufferAttribute(u,1));g.setAttribute('aV',new THREE.BufferAttribute(v,1));g.setAttribute('aPart',new THREE.BufferAttribute(part,1));this.material=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uScale:{value:1},uSpeed:{value:1},uPulse:{value:1},uTurbulence:{value:.3},uDeformation:{value:1},uPhase:{value:1},uAppendages:{value:8},uAspectX:{value:1},uAspectY:{value:1},uBody:{value:0},uMotion:{value:1},uSymmetry:{value:1},uPointerX:{value:99},uPointerY:{value:99},uParticleSize:{value:2.2},uHue:{value:0},uSaturation:{value:1},uBrightness:{value:1},uGlow:{value:1},uColorA:{value:color('#6cf4ff')},uColorB:{value:color('#ae7dff')},uColorC:{value:color('#fff')}}});this.points=new THREE.Points(g,this.material);this.scene.add(this.points)}
 update(creature:Creature,controls:Controls){if(this.disposed)return;const requested=Math.min(controls.density,this.maxParticles);if(!this.material||this.count!==requested)this.build(requested);const u=this.material.uniforms,b={bell:0,mantle:1,radial:2,carapace:3,segmented:4,curved:5}[creature.body];u.uScale.value=controls.scale;u.uSpeed.value=controls.speed;u.uPulse.value=controls.pulse;u.uTurbulence.value=controls.turbulence;u.uDeformation.value=controls.deformation*creature.deformation;u.uPhase.value=controls.phase*creature.phase;u.uAppendages.value=controls.appendages||creature.appendages;u.uMotion.value=creature.motion;u.uSymmetry.value=creature.symmetry;u.uAspectX.value=creature.aspect[0];u.uAspectY.value=creature.aspect[1];u.uBody.value=b;u.uParticleSize.value=controls.size;u.uHue.value=controls.hue;u.uSaturation.value=controls.saturation;u.uBrightness.value=controls.brightness;u.uGlow.value=controls.glow;u.uColorA.value.set(creature.palette[0]);u.uColorB.value.set(creature.palette[1]);u.uColorC.value.set(creature.palette[2]);this.bloom.strength=.18+Math.min(controls.glow,3)*.32;this.bloom.radius=.18+Math.min(controls.glow,3)*.1;this.bloom.threshold=.72+Math.min(controls.glow,3)*.06;this.afterimage.uniforms.damp.value=THREE.MathUtils.lerp(.05,.88,controls.trail)}
 render(paused:boolean){if(this.disposed||!this.material)return;if(!paused)this.material.uniforms.uTime.value=(performance.now()-this.start)/1000;this.material.uniforms.uPointerX.value=this.pointer.x*1.5;this.material.uniforms.uPointerY.value=this.pointer.y;if(this.enableParallax){this.camera.position.x+=(this.cameraTarget.x-this.camera.position.x)*.045;this.camera.position.y+=(this.cameraTarget.y-this.camera.position.y)*.045;this.camera.lookAt(0,0,0)}this.composer.render()}
 dispose(){if(this.disposed)return;this.disposed=true;this.resizeObserver.disconnect();this.renderer.domElement.removeEventListener('pointermove',this.onPointerMove);this.renderer.domElement.removeEventListener('pointerleave',this.onPointerLeave);if(this.points)this.points.geometry.dispose();if(this.material)this.material.dispose();this.composer.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}